services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8081:8081"
    volumes:
      - .:/usr/src/app
    command: air cmd/app/main.go -b 0.0.0.0
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: journaly-db
    restart: unless-stopped
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: journaly
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
