services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8081:8081"
    volumes:
      - .:/usr/src/app
    command: air cmd/app/main.go -b 0.0.0.0
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
